### PR TITLE
Add support for PT_BR lang

### PR DESCRIPTION
**Pull request by ludioao**

### CODE REVIEW

**Comment by miquelbeltran** [comment]
Hey @ludioao thanks for the idea.

I am not sure if we want to add more localizations as there's no easy way to maintain them at the moment.

What do you think @fheinfling ??

Also, this PR is incomplete, the backend also requires translations, see: https://github.com/janoodleFTW/timy-messenger/blob/master/firebase/functions/localize-util.js
although it would go default to English, I think is good to keep consistency.

**Comment by arvanus** [comment]
It would be nice to support translation.
It doesn't need to be 100% translated to help some users

**Comment by ludioao** [comment]
@miquelbeltran as you mentioned, i think we can do a better translation engine inside backend... 

many conditional cases wouldnt it be good

**Comment by miquelbeltran** [comment]
That's why I am not so convinced about adding more languages, the whole localization solution could be better and I think it would be good to improve that part first. But I'd like to hear what @fheinfling thinks.

**Comment by fheinfling** [comment]
This is indeed an open issue. We've already started moving parts of our localization back to our clients. The idea is now to provide only keys and necessary values to our clients.
A a first attempt has been made in https://github.com/janoodleFTW/timy-messenger/blob/6a33ee47399ee7beb111f4edaee6ef71bfe5d932/firebase/functions/rsvp-update.js#L47

Our clients then process it here:
https://github.com/janoodleFTW/timy-messenger/blob/6a33ee47399ee7beb111f4edaee6ef71bfe5d932/lib/circles_localization.dart#L504

I'd agree with @arvanus. I think it's okay to have this (client only) translation in for a start.

**Pull request merged**
